[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "my_package"
version = "0.1.0"
description = "A simple calculator package"
authors = [{ name = "Khurram Saleem", email = "youremail@example.com" }]
dependencies = []
